export const CONDITIONS: Record<ConditionType, string> = {
    shaken: "Abalado",
    grappled: "Agarrado",
    frightened: "Amedrontado",
    stunned: "Atordoado",
    prone: "Caído",
    blinded: "Cego",
    doomed: "Condenado",
    confused: "Confuso",
    dazed: "Desorientado",
    "flat-footed": "Desprevenido",
    charmed: "Enfeitiçado",
    sickened: "Enjoado",
    entangled: "Enredado",
    poisoned: "Envenenado",
    exposed: "Exposto",
    weakened: "Fragilizado",
    immobile: "Imóvel",
    incapacitated: "Incapacitado",
    unconscious: "Inconsciente",
    invisible: "Invisível",
    slowed: "Lento",
    paralyzed: "Paralisado",
    bleeding: "Sangramento",
    deafened: "Surdo",
};